### ISSUE TITLE
Create and Setup, Step 9 -- bad github link

### ISSUE THREAD

**Issue by GloriaAnholt** [codefellows/portland-301d6#1]
Under the https://github.com/codefellows/portland-301d6#create-and-setup-your-301-directory-structure section, you have two incorrect links:

9.  Type git remote add upstream https://github.com/codefellows/seattle-301d7.git to enable quick access to future updates.

https://github.com/codefellows/seattle-301d7.git

As we're the Portland class, this should probably read:

https://github.com/codefellows/portland-301d6.git

16. Back here on GitHub, head to the separate GitHub site where all lab assignments can be found: https://github.com/codefellows-portland-301d5

This link should probably read:

https://github.com/codefellows-portland-301d6

Cheers!
Gloria

**Comment by aaroncrows** [comment]
Got it, thanks!
